#! /bin/bash

echo "SCRIPT	: buildzip"
echo "HELP	: build zip file for Arduino installation"

rm -rf ziptmp
mkdir -p ziptmp/libraries
mkdir -p ziptmp/FireStep

pushd ../ph5 >& /dev/null
scripts/buildzip
popd >& /dev/null
mv ../ph5*.zip ziptmp
pushd ArduinoJson >& /dev/null
scripts/buildzip
popd >& /dev/null
mv ArduinoJson*.zip ziptmp

TAG=`git log --pretty=format:'%H' -n 1`
OUTPUT="FireStep-$TAG.zip"
echo "CMD	: creating $OUTPUT"

cp -r DueTimer/ ziptmp/libraries
cp -r FireStep/ ziptmp/FireStep
cp CHANGELOG.md LICENSE README.md ziptmp/FireStep
cp target/git_tag.h ziptmp/FireStep/FireStep

pushd ziptmp/libraries >& /dev/null
unzip -q ../ph5*.zip
unzip -q ../ArduinoJson*.zip
popd >& /dev/null

pushd ziptmp >& /dev/null
zip -r -q $OUTPUT \
	FireStep \
	libraries
popd >& /dev/null
