#! /bin/bash

echo "SCRIPT	: buildzip"
echo "HELP	: build zip file for Arduino installation"

TAG=`git log --pretty=format:'%H' -n 1`
OUTPUT="FireStep-$TAG.zip"
echo "STATUS	: creating $OUTPUT"

rm -rf ziptmp
mkdir -p ziptmp/libraries
mkdir -p ziptmp/FireStep
echo "TAG	: $TAG" | tee ziptmp/FireStep/tag

pushd ../ph5
scripts/buildzip
popd
mv ../ph5*.zip ziptmp
pushd ArduinoJson
scripts/buildzip
popd
mv ArduinoJson*.zip ziptmp

cp -r FireStep/ ziptmp/FireStep
cp CHANGELOG.md LICENSE README.md ziptmp/FireStep

cd ziptmp/libraries
unzip -q ../ph5*.zip
unzip -q ../ArduinoJson*.zip

cd ..

zip -r -q $OUTPUT \
	FireStep \
	libraries
