#!/bin/bash

firestep < scripts/cal-fpd-home.json >> /tmp/data
firestep < scripts/cal-fpd-home.json >> /tmp/data
firestep < scripts/cal-fpd-home.json >> /tmp/data
firestep < scripts/cal-fpd-home.json >> /tmp/data
firestep < scripts/cal-fpd-home.json >> /tmp/data
firestep < scripts/cal-fpd-home.json >> /tmp/data
firestep < scripts/cal-fpd-home.json >> /tmp/data
firestep < scripts/cal-fpd-home.json >> /tmp/data
firestep < scripts/cal-fpd-home.json >> /tmp/data
firestep < scripts/cal-fpd-home.json >> /tmp/data
firestep < scripts/cal-fpd-home.json >> /tmp/data
firestep < scripts/cal-fpd-home.json >> /tmp/data
firestep < scripts/cal-fpd-home.json >> /tmp/data
firestep < scripts/cal-fpd-home.json >> /tmp/data
firestep < scripts/cal-fpd-home.json >> /tmp/data
firestep < scripts/cal-fpd-home.json >> /tmp/data
firestep < scripts/cal-fpd-home.json >> /tmp/data
firestep < scripts/cal-fpd-home.json >> /tmp/data
firestep < scripts/cal-fpd-home.json >> /tmp/data
firestep < scripts/cal-fpd-home.json >> /tmp/data
