#!/bin/bash
echo "CMD	: release FireStep"
rm -rf ~/Arduino/FireStep/
rm ~/Downloads/FireStep-*.zip
rm ~/Downloads/ArduinoJson-*.zip
scripts/buildzip
mv -v ziptmp/*.zip ~/Downloads
pushd ~/Arduino >& /dev/null
unzip -oq ~/Downloads/FireStep-*.zip
popd >& /dev/null
echo "STATUS	: Installed"
